//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLtd
{
    using System;
    using System.Collections.Generic;
    
    public partial class activitylog
    {
        public int actlogID { get; set; }
        public int StaffID { get; set; }
        public string logType { get; set; }
        public string Interface { get; set; }
        public System.DateTime logDate { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
