//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLtd
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryorder
    {
        public int delorderID { get; set; }
        public Nullable<int> salorderID { get; set; }
        public Nullable<int> reorderID { get; set; }
        public Nullable<int> del_StaffID { get; set; }
        public string delStatus { get; set; }
        public string Address { get; set; }
        public int isValid { get; set; }
        public System.DateTime delReqDate { get; set; }
        public string delReqPeriod { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual salesorder salesorder { get; set; }
    }
}
