//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLtd
{
    using System;
    using System.Collections.Generic;
    
    public partial class installorder
    {
        public int insorderID { get; set; }
        public int salorderID { get; set; }
        public Nullable<int> ins_StaffID { get; set; }
        public string insStatus { get; set; }
        public string Address { get; set; }
        public int isValid { get; set; }
        public System.DateTime insReqDate { get; set; }
        public string insReqPeriod { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual salesorder salesorder { get; set; }
    }
}
