//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLtd
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int orderID { get; set; }
        public int receiptID { get; set; }
        public int payID { get; set; }
        public int CustomerID { get; set; }
        public int CardNum { get; set; }
        public decimal totalPrice { get; set; }
    }
}
