//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLtd
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salesorder()
        {
            this.deliveryorders = new HashSet<deliveryorder>();
            this.installorders = new HashSet<installorder>();
        }
    
        public int salorderID { get; set; }
        public int StoreID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int StaffID { get; set; }
        public decimal totalPrice { get; set; }
        public System.DateTime dateCreated { get; set; }
        public int isValid { get; set; }
        public int isPanding { get; set; }
        public int NeedDelivery { get; set; }
        public int NeedInstall { get; set; }
        public int isArranged { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installorder> installorders { get; set; }
        public virtual retailstore retailstore { get; set; }
        public virtual staff staff { get; set; }
    }
}
