//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLtd
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesorder_detail
    {
        public int dummypk { get; set; }
        public int salorderID { get; set; }
        public int prodID { get; set; }
        public string prodName { get; set; }
        public decimal price { get; set; }
        public int qty { get; set; }
        public int Total { get; set; }
        public int isValid { get; set; }
    }
}
