//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLtd
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_stock
    {
        public int StoreID { get; set; }
        public int prodID { get; set; }
        public string category { get; set; }
        public string brand { get; set; }
        public int qty { get; set; }
        public int lowlevel { get; set; }
    
        public virtual product product { get; set; }
        public virtual retailstore retailstore { get; set; }
    }
}
