//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLtd
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_reorder
    {
        public int reordID { get; set; }
        public int StaffID { get; set; }
        public int warehouseID { get; set; }
        public int prodID { get; set; }
        public string prodName { get; set; }
        public string status { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> approveDate { get; set; }
        public string inward_status { get; set; }
    
        public virtual product product { get; set; }
        public virtual staff staff { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
